# Generated by Django 4.2.1 on 2024-03-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_hours_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credit_hours_min',
            field=models.IntegerField(null=True),
        ),
    ]
