# Generated by Django 4.2.1 on 2024-03-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_course_credit_hours_max_course_credit_hours_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
