# Generated by Django 4.2.1 on 2024-03-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_course_major_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprerequisite',
            name='minimum_grade',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
