# Generated by Django 4.2.1 on 2024-03-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_courseprerequisite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprerequisite',
            name='type',
            field=models.CharField(choices=[('COURSE', 'COURSE'), ('GROUP', 'GROUP')], db_index=True, max_length=255),
        ),
    ]
