# Generated by Django 4.2.1 on 2024-03-10 04:29

import Backend.utils.snowflake
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_courseprerequisite_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigIntegerField(default=Backend.utils.snowflake.generate_uid, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('short_name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('parent_major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major_parent_major', to='models.major')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
