# Generated by Django 4.2.1 on 2024-03-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_alter_course_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=models.TextField(db_index=True, null=True),
        ),
    ]
