# Generated by Django 4.2.1 on 2024-03-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_course_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='keywords',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
